### ISSUE TITLE
Del 功能添加

### ISSUE THREAD

**Issue by KNWking** [lc6464/MyTan-Enhancer#11]
能否添加在 Chat 界面，非输入情况下键入 `Del` 时，如果存在非置顶对话，则全部删除的功能？

**Comment by lc6464** [comment]
理论上很容易实现，实际上太过危险，暂时没有实现的计划，如有更多信息欢迎重开议题。

**Comment by KNWking** [comment]
了解了。下次我争取做出有效的贡献，耽误了。
